# Generated by Django 4.2.6 on 2023-10-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enginedata',
            name='user',
        ),
        migrations.AddIndex(
            model_name='enginedata',
            index=models.Index(fields=['temperature_engine_coolant'], name='telemetry_e_tempera_362e2e_idx'),
        ),
    ]
