# Generated by Django 4.2.6 on 2023-10-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_remove_enginedata_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brakedata',
            name='user',
        ),
    ]
