# Generated by Django 4.2.6 on 2023-10-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_remove_brakedata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coolingsystemdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='diagnosticsdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='electricalsystemdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fueldata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transmissiondata',
            name='user',
        ),
    ]
