# Generated by Django 4.2.6 on 2023-10-27 10:12

import customManager.models.services_model
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Exclusão')),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Exclusão')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceito'), ('DECLINED', 'Recusado')], max_length=50)),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamento',
            },
        ),
        migrations.CreateModel(
            name='HourService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Exclusão')),
                ('hour', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Hora deve estar no formato HH:MM', regex='^([0-1][0-9]|2[0-3]):[0-5][0-9]$')], verbose_name='Hora Serviço')),
            ],
            options={
                'verbose_name': 'Horário de Atendimento',
                'verbose_name_plural': 'Horários de Atendimento',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Exclusão')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Numero Pedido')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('due_date', models.DateField(verbose_name='Data')),
                ('status', models.CharField(choices=[('PAID', 'Pago'), ('UNPAID', 'Não Pago'), ('OVERDUE', 'Vencido')], max_length=50, verbose_name='Andamento')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamento',
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Exclusão')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Histório de Serviço',
                'verbose_name_plural': 'Histório de Serviços',
                'ordering': ['-deleted_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Exclusão')),
                ('name', models.CharField(max_length=255, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to=customManager.models.services_model.get_file_path, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Exclusão')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('fuel', models.CharField(max_length=50, verbose_name='Combustível')),
                ('year', models.CharField(max_length=4, verbose_name='Ano')),
                ('odometer', models.CharField(max_length=20, verbose_name='Hodometro')),
                ('plate', models.CharField(max_length=15, unique=True, verbose_name='Placa')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Chassi')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-deleted_at', '-updated_at', 'year', 'brand', 'plate', 'vin'],
            },
        ),
    ]
