# Generated by Django 4.2.6 on 2023-10-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customManager', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['cep'], name='customManag_cep_3c93ba_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['status'], name='customManag_status_19667f_idx'),
        ),
        migrations.AddIndex(
            model_name='hourservice',
            index=models.Index(fields=['hour'], name='customManag_hour_2cf9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='customManag_invoice_96b58c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicehistory',
            index=models.Index(fields=['name'], name='customManag_name_ccf7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['name'], name='customManag_name_2c3189_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate'], name='customManag_plate_38d6f0_idx'),
        ),
    ]
